version: "3.8"

services: 
  db:
    image: mysql:5.7
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: fresh_everyday
      MYSQL_ROOT_PASSWORD: dailyfresh
    volumes:
      - ./data.sql:/sql_scripts/DailyFresh/data.sql

  web:
    build: .
    command: bash -c "python3 ./wait_for_mysql.py db 3306 root dailyfresh fresh_everyday && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:9000"
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
  
  cache:
    image: redis:latest
